# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

ruby '3.0.0'

gem 'puma', '~> 5.2.0'
gem 'rake', '~> 13.0.0'
gem 'roda', '~> 3.41.0'

gem 'config', '~> 3.0.0'
gem 'i18n', '~> 1.8.0'

gem 'pg', '~> 1.2.3'
gem 'sequel', '~> 5.42.0'

gem 'dry-initializer', '~> 3.0.0'
gem 'dry-validation', '~> 1.6.0'

gem 'activesupport', '~> 6.1.0', require: false

gem 'slim', '~> 4.1.0'
gem 'sassc', '~> 2.4.0'
gem 'forme', '~> 1.11.0'

group :development, :test do
  gem 'pry-byebug', '~> 3.9.0'
  gem 'rubocop', '~> 1.11.0', require: false

  gem 'database_cleaner-sequel', '~> 2.0.0'
  gem 'fabrication', '~> 2.21.0'
  gem 'rack-test', '~> 1.1.0'
  gem 'rspec', '~> 3.10.0'
  gem 'rspec_sequel_matchers', '~> 0.5.0'

  gem 'rack-unreloader', '~> 1.7.0'
end
